### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by frcroth** [HoubkneghteS/Weltenschaft#3]
Hi!
I am interested in this project and would like to try it out myself, is there a guide on running it locally? I didn't find anything on the wiki or in the README.md.
Windows, Linux or docker would be fine.

**Comment by HoubkneghteS** [comment]
I should probably get around to creating a guide sometime. In the meantime, there are 2 ways:

(both of these apply to Windows)

1. Install one of the packaged zip files that contain final versions. This is the way I recommend, since it is less likely to contain bugs or other issues, but it also takes longer to get the newest features.

2. Clone the project locally, and install Node, and then install all the dependencies by running cmd in the project folder and typing `npm install`. 

Feel free to ask any further questions!

**Comment by frcroth** [comment]
Thanks for the quick answer!
Number one worked well.
